FROM node:12-alpine

COPY ./containers/dredd /app/main-runner
COPY ./repos/dredd /app/main

WORKDIR /app/main/packages/dredd-transactions

RUN npm install

WORKDIR /app/main/packages/dredd

RUN npm install

WORKDIR /app/main-runner

RUN npm install

CMD node ./main.js
